### PR TITLE
Correct mistake in regex example

### PR DESCRIPTION
**Pull request by gene1wood**
This is an alternative solution the problem identified in #158 that only corrects the regex mistake but doesn't add a good example and a bad example. The original mistake was introduced in d40a73f25f20fc1da4815e2b8644055479e9fd21 and then I overlooked it in #41.

### CODE REVIEW

**Comment by ypid** [comment]
Could you make me the author of that commit? You can stay the committer. Git makes that difference for a reason ;-)

**Review by osostest — COMMENTED** [review]
Test

**Comment by gene1wood** [comment]
@ypid I'm not sure how to change the author on the commit. Feel free to create a new PR based and I can close this one out.

**Comment by ypid** [comment]
Sure, done that: #393

**Comment by gene1wood** [comment]
See #393 for the same content authored by @ypid

**Pull request closed without merging**
