### PR TITLE
Q1 Release

### PR DESCRIPTION
**Pull request by fschillingeriv**
Documentation additions for Q1 Release Items:

- Emergency Access
- Encrypted Exports
- Custom Role
- Personal Ownership Policy
- Biometric Unlock for Browser Extensions 

Plus, some small requested fixes from the team and AML Implementation samples for AWS and AUTH0.

### CODE REVIEW

**Review by tgreer-bw — DISMISSED** [review]

**Review by tgreer-bw — APPROVED** [review]

**Comment by vachan-maker** [comment]
@fschillingeriv Help documents does not mention Emergency Access is  a premium feature. The pricing and plans page should also highlight Emergency Access as  premium feature.

**Comment by tgreer-bw** [comment]
help is updated, website updates will come soon.

**Comment by vachan-maker** [comment]
> 
> 
> help is updated, website updates will come soon.

Thanks @fschillingeriv and @tgreer-bw . Also, there is question in the FAQ. Does Bitwarden have emergency access?. Can you update that as well?

**Comment by tgreer-bw** [comment]
Yep, we're reviewing lots of items at the moment and cleaning up references :-)

**Comment by fschillingeriv** [comment]
@vachan-maker PRs are in to fix both those items, thanks for bringing them to our attention! Plans & Pricing updates coming soon.

**Pull request merged**
