### PR TITLE
Add guide for changing email address

### PR DESCRIPTION
**Pull request by ple103**

### CODE REVIEW

**Comment by kspearrin** [comment]
Some big changes to the help site are about to be pushed so make sure that you pull next time before doing any more. Thanks!

**Comment by ple103** [comment]
@kspearrin Sweet. Thanks for letting me know! Are we going to be adopting Mendix docs?

**Comment by kspearrin** [comment]
I am not familiar with Mendix docs. It's still jekyll I just reorganized everything and am in the middle of applying a new design to match the main website. You can pull now (still a WIP though).

**Comment by kspearrin** [comment]
@ple103 Also, you will need to do a `npm install`, `gulp build` now as well before starting your `jekyll serve`. You should only need to do this once since libs and things won't be changing.

**Comment by ple103** [comment]
Thanks for the heads up. I will update the README and create a PR (won't happen in the next few hours though). Looking forward to the new design too.

**Comment by kspearrin** [comment]
@ple103 new help site is up and running live now: https://help.bitwarden.com

**Comment by kspearrin** [comment]
@ple103 Most of my work with the refactor of the help site is now complete.

Note that I created several new helper tags for things like notes, warnings, tips, images, callouts, and alerts. You can see how I am using them in other articles.

**Pull request merged**
