### PR TITLE
Added path for Edge in macOS

### PR DESCRIPTION
**Pull request by Greenderella**
Did anybody know it was possible to use Edge on macOS? The times we live in!

### CODE REVIEW

**Review by tgreer-bw — APPROVED** [review]

**Comment by vachan-maker** [comment]
Microsoft Edge is also coming to Linux. Currently, it is in beta

**Comment by Greenderella** [comment]
> Microsoft Edge is also coming to Linux. Currently, it is in beta

Beautiful

image

**Comment by vachan-maker** [comment]
> 
> 
> > Microsoft Edge is also coming to Linux. Currently, it is in beta
> 
> Beautiful
> 
> image

Aaah, you are lucky. I tried to install ubuntu on my windows machine and failed. When I flashed the ISO, my usb drive died because I did something stupid😂😂. Now the drive is in read only mode.

**Comment by vachan-maker** [comment]
> 
> 
> Did anybody know it was possible to use Edge on macOS? The times we live in!

By the way, Is bitwarden available on the legacy version of Edge?

**Comment by tgreer-bw** [comment]
> > 
> 
> > 
> 
> > Did anybody know it was possible to use Edge on macOS? The times we live in!
> 
> 
> 
> By the way, Is bitwarden available on the legacy version of Edge? 

It's no longer supported as of the last release. Only the Chromium based version is supported currently.

**Pull request merged**
